- name: funtions
  hosts: local
  connection: local
  vars:
    technologies: Devops, linix, AWS
    dic:
      application: payement
      region: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Ramesh') }}"
  
  - name: strings to list
    ansible.builtin.debug:
      msg: "changing strings to list{{ technologies| split(',') }}"
  
  - name: covnvert map means dictionary to list
    ansible.builtin.debug:
      msg: "converting maps to list {{ dic | dict2items }}"
